<script setup lang="ts">
import { computed } from 'vue';
import { Head } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';

type GroupTeam = {
  id: string;
  displayName: string;
  seed: number | null;
};

type Group = {
  id: string;
  category_id: string;
  categoryName?: string | null;
  tournamentName?: string | null;
  name: string;
  matchesCount: number;
  teams: GroupTeam[];
};

type CategorySection = {
  key: string;
  categoryName: string;
  tournamentName: string;
  groups: Group[];
};

const props = defineProps<{
  groups: Group[];
}>();

// Groups arrive flat and name-ordered. Bucket them by category so the read
// view renders one section per category, preserving the incoming order.
const sections = computed<CategorySection[]>(() => {
  const byCategory = new Map<string, CategorySection>();
  for (const group of props.groups) {
    const key = group.category_id;
    let section = byCategory.get(key);
    if (!section) {
      section = {
        key,
        categoryName: group.categoryName || 'Uncategorized',
        tournamentName: group.tournamentName || '—',
        groups: [],
      };
      byCategory.set(key, section);
    }
    section.groups.push(group);
  }
  return [...byCategory.values()];
});

// Inside a single group, list seeded teams first (ascending), unseeded last.
function sortedTeams(teams: GroupTeam[]): GroupTeam[] {
  return [...teams].sort((a, b) => {
    if (a.seed === null && b.seed === null) return 0;
    if (a.seed === null) return 1;
    if (b.seed === null) return -1;
    return a.seed - b.seed;
  });
}
</script>

<template>
  <Head title="Groups" />
  <AdminLayout>
    <div class="flex items-center justify-between mb-5">
      <h1 class="text-2xl font-bold text-slate-900">Groups</h1>
      <span class="chip chip-soon">Read-only</span>
    </div>

    <div v-if="props.groups.length === 0" class="card text-center">
      <div class="text-4xl mb-2">🗂️</div>
      <p class="text-slate-500">No groups yet.</p>
      <p class="text-sm text-slate-400 mt-1">Groups are generated by the draw command.</p>
    </div>

    <div v-else class="space-y-8">
      <section v-for="section in sections" :key="section.key">
        <div class="flex flex-wrap items-baseline gap-x-2 gap-y-1 mb-3">
          <h2 class="text-lg font-bold text-slate-900">{{ section.categoryName }}</h2>
          <span class="text-sm text-slate-400">{{ section.tournamentName }}</span>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <div v-for="group in section.groups" :key="group.id" class="card p-0 overflow-hidden">
            <div class="flex items-center justify-between px-4 py-3 border-b border-slate-100">
              <h3 class="font-semibold text-slate-900">{{ group.name }}</h3>
              <span class="chip chip-done">{{ group.matchesCount }} {{ group.matchesCount === 1 ? 'match' : 'matches' }}</span>
            </div>

            <ul v-if="group.teams.length" class="divide-y divide-slate-100">
              <li
                v-for="team in sortedTeams(group.teams)"
                :key="team.id"
                class="flex items-center gap-3 px-4 py-2.5 text-sm"
              >
                <span
                  v-if="team.seed !== null"
                  class="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-50 text-xs font-bold text-brand-700 ring-1 ring-brand-200"
                >
                  {{ team.seed }}
                </span>
                <span
                  v-else
                  class="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-400 ring-1 ring-slate-200"
                >
                  —
                </span>
                <span class="font-medium text-slate-800 truncate">{{ team.displayName || 'Unnamed team' }}</span>
              </li>
            </ul>

            <p v-else class="px-4 py-4 text-sm text-slate-400">No teams assigned.</p>
          </div>
        </div>
      </section>
    </div>
  </AdminLayout>
</template>
