<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Enums\MatchStage;
use App\Enums\MatchStatus;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\MatchResultRequest;
use App\Http\Requests\Admin\MatchUpdateRequest;
use App\Models\Court;
use App\Models\MatchModel;
use App\Models\MatchSet;
use App\Models\Team;
use App\Services\Scoring\AdminResultService;
use App\Services\Scoring\ScoringService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Manage matches at the schedule level: assign a court, scheduled time, and
 * status. Matches are generated by the bracket/draw engine, so there is no
 * create/destroy here — only index + edit/update.
 */
class MatchController extends Controller
{
    public function __construct(
        private readonly AdminResultService $results,
        private readonly ScoringService $scoring,
    ) {
    }

    /**
     * GET /manage/matches
     */
    public function index(): Response
    {
        $matches = MatchModel::query()
            ->with($this->eagerLoads())
            ->with(['sets' => fn ($q) => $q->orderBy('set_number')])
            ->orderByRaw('scheduled_at IS NULL, scheduled_at ASC')
            ->orderBy('created_at')
            ->get()
            ->map(function (MatchModel $m): array {
                $row = $this->serialize($m);
                $row['sets'] = $this->serializeSets($m);
                $row['winnerName'] = $this->winnerName($m);

                return $row;
            })
            ->all();

        return Inertia::render('Admin/Matches/Index', [
            'matches' => $matches,
        ]);
    }

    /**
     * GET /manage/matches/{match}/edit
     */
    public function edit(MatchModel $match): Response
    {
        $match->load($this->eagerLoads());
        $match->load(['sets' => fn ($q) => $q->orderBy('set_number')]);
        $match->loadMissing('tournament');

        $config = $this->scoring->configForMatch($match);

        return Inertia::render('Admin/Matches/Edit', [
            'match' => $this->serialize($match),
            'sets' => $this->serializeSets($match),
            'scoringConfig' => [
                'pointsToWin' => $config['pointsToWin'],
                'setsToWin' => $config['setsToWin'],
                'deuceCap' => $config['deuceCap'],
            ],
            'courts' => $this->courtOptions($match),
            'statuses' => MatchStatus::labels(),
            'stages' => MatchStage::labels(),
        ]);
    }

    /**
     * PUT /admin/matches/{match}/result
     *
     * Admin bulk result: derive winner from entered set scores and persist.
     */
    public function result(MatchResultRequest $request, MatchModel $match): RedirectResponse
    {
        if ($match->team_a_id === null || $match->team_b_id === null) {
            throw ValidationException::withMessages([
                'sets' => 'Teams not determined yet for this match.',
            ]);
        }

        $this->results->recordResult($match, $request->sets(), $request->user());

        return redirect()
            ->route('admin.matches.edit', ['match' => $match->id])
            ->with('success', 'Result recorded.');
    }

    /**
     * PUT /admin/matches/{match}/walkover
     *
     * Declare a walkover for one of the two teams.
     */
    public function walkover(Request $request, MatchModel $match): RedirectResponse
    {
        $validated = $request->validate([
            'winner_team_id' => ['required', 'string', 'uuid'],
        ]);

        if ($match->team_a_id === null || $match->team_b_id === null) {
            throw ValidationException::withMessages([
                'winner_team_id' => 'Teams not determined yet for this match.',
            ]);
        }

        $winnerId = $validated['winner_team_id'];
        if ($winnerId !== $match->team_a_id && $winnerId !== $match->team_b_id) {
            throw ValidationException::withMessages([
                'winner_team_id' => 'Winner must be one of the match teams.',
            ]);
        }

        /** @var Team $winner */
        $winner = Team::query()->findOrFail($winnerId);

        $this->results->walkover($match, $winner, $request->user());

        return redirect()
            ->route('admin.matches.edit', ['match' => $match->id])
            ->with('success', 'Walkover recorded.');
    }

    /**
     * PUT /admin/matches/{match}/reset
     *
     * Clear the result back to SCHEDULED and drop bracket propagation.
     */
    public function reset(MatchModel $match): RedirectResponse
    {
        $this->results->resetResult($match);

        return redirect()
            ->route('admin.matches.edit', ['match' => $match->id])
            ->with('success', 'Result cleared.');
    }

    /**
     * PUT /manage/matches/{match}
     */
    public function update(MatchUpdateRequest $request, MatchModel $match): RedirectResponse
    {
        $match->update($request->validated());

        return redirect()
            ->route('admin.matches.index')
            ->with('success', 'Match updated.');
    }

    /**
     * @return array<string, \Closure|string>
     */
    private function eagerLoads(): array
    {
        return [
            'category:id,tournament_id,type,name',
            'court:id,name',
            'teamA:id,category_id,display_name,seed',
            'teamB:id,category_id,display_name,seed',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function serialize(MatchModel $m): array
    {
        return [
            'id' => $m->getKey(),
            'tournament_id' => $m->tournament_id,
            'category_id' => $m->category_id,
            'categoryName' => $m->category?->name,
            'court_id' => $m->court_id,
            'courtName' => $m->court?->name,
            'stage' => $m->stage?->value,
            'status' => $m->status?->value,
            'round_number' => $m->round_number,
            'bracket_slot' => $m->bracket_slot,
            // Stored UTC; admin edits in Asia/Yangon. <input type="datetime-local">
            // wants "YYYY-MM-DDTHH:mm" in local (Yangon) time.
            'scheduledAt' => $m->scheduled_at?->copy()->setTimezone('Asia/Yangon')->format('Y-m-d\TH:i'),
            'startedAt' => $m->started_at?->toIso8601String(),
            'completedAt' => $m->completed_at?->toIso8601String(),
            'teamA' => $this->serializeTeam($m->teamA, $m->team_a_source),
            'teamB' => $this->serializeTeam($m->teamB, $m->team_b_source),
            'teamsResolved' => $m->team_a_id !== null && $m->team_b_id !== null,
            'winnerId' => $m->winner_id,
            'notes' => $m->notes,
        ];
    }

    /**
     * Serialize one side of a match. When the team is still null (unresolved
     * knockout slot) we return a placeholder shaped the same way, with id null
     * and a human label derived from the bracket source ("Winner of …",
     * "1st of Group A", etc.) so the admin sees who *will* play.
     *
     * @return array{id:string|null,displayName:string,resolved:bool}
     */
    private function serializeTeam(mixed $team, ?string $source): array
    {
        if ($team === null) {
            return [
                'id' => null,
                'displayName' => $this->sourceLabel($source),
                'resolved' => false,
            ];
        }

        return [
            'id' => $team->getKey(),
            'displayName' => $team->display_name ?? '',
            'resolved' => true,
        ];
    }

    /**
     * Human-readable placeholder for an unresolved bracket slot from its
     * source string. "G:A:1" -> "1st of Group A"; "W:<uuid>" -> "Winner of
     * prior match"; "L:<uuid>" -> "Loser of prior match"; unknown -> "TBD".
     */
    private function sourceLabel(?string $source): string
    {
        if ($source === null || $source === '') {
            return 'TBD';
        }

        if (str_starts_with($source, 'G:')) {
            $parts = explode(':', $source);
            $letter = $parts[1] ?? '';
            $pos = (int) ($parts[2] ?? 0);
            $ordinal = match ($pos) {
                1 => '1st',
                2 => '2nd',
                3 => '3rd',
                default => $pos . 'th',
            };

            return $letter === '' ? "{$ordinal} of group" : "{$ordinal} of Group {$letter}";
        }

        if (str_starts_with($source, 'W:')) {
            return 'Winner of prior match';
        }
        if (str_starts_with($source, 'L:')) {
            return 'Loser of prior match';
        }

        return 'TBD';
    }

    /**
     * Current set scores for the match, ordered by set number.
     *
     * @return list<array{setNumber:int,teamAScore:int,teamBScore:int,winnerId:string|null}>
     */
    private function serializeSets(MatchModel $m): array
    {
        return $m->sets
            ->sortBy('set_number')
            ->values()
            ->map(fn (MatchSet $s): array => [
                'setNumber' => (int) $s->set_number,
                'teamAScore' => (int) $s->team_a_score,
                'teamBScore' => (int) $s->team_b_score,
                'winnerId' => $s->winner_id,
            ])
            ->all();
    }

    /**
     * Display name of the winning team for a completed match, or null.
     */
    private function winnerName(MatchModel $m): ?string
    {
        if ($m->winner_id === null) {
            return null;
        }

        if ($m->teamA && $m->teamA->getKey() === $m->winner_id) {
            return $m->teamA->display_name;
        }
        if ($m->teamB && $m->teamB->getKey() === $m->winner_id) {
            return $m->teamB->display_name;
        }

        return null;
    }

    /**
     * Courts belonging to the same tournament as the match.
     *
     * @return list<array<string, string>>
     */
    private function courtOptions(MatchModel $match): array
    {
        return Court::query()
            ->where('tournament_id', $match->tournament_id)
            ->select(['id', 'name'])
            ->orderBy('display_order')
            ->orderBy('name')
            ->get()
            ->map(fn (Court $c): array => [
                'id' => $c->getKey(),
                'name' => $c->name,
            ])
            ->all();
    }
}
